### ISSUE TITLE
冯如杯

### ISSUE THREAD

**Issue by sdlyyxy** [MrDxxK/Air-pollution-monitor#2]
冯如杯英文名是Feng Ru Cap，而非FengRu Cup。见en.fengru.net
--吹毛求疵系列之二

**Comment by sdlyyxy** [comment]
en.fengrubei.net ........

**Comment by MrJaxK** [comment]
已收到并改正

**Comment by sdlyyxy** [comment]
其实这个名称他们学校也不统一……参见那个网页的正文……
